version: 2
jobs:
  build:
    docker:
      - image: python:2.7-alpine3.6
        environment:
          PYTHONUSERBASE: /app/vendor
          PYTHONPATH: '/app/vendor/lib/python2.7/site-packages'
          PATH: '/app/vendor/bin:/usr/local/bin:$PATH'
    working_directory: /app/
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run: pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "/app/vendor/cache/.requirements-cache"
      - run: python -m pytest --cov=life
      - run: behave --junit
      - store_artifacts:
          path: reports
      - store_test_results:
          path: reports